### PR TITLE
Closes #77

### LINKED ISSUE #77: Implement Puppeteer testing framework
References user story #73

Implement Puppeteer for our project.

Definition of done:

- [x] Puppeteer is fully implemented and ready for system tests to be added
- [x] Add example test

### PR DESCRIPTION
**Pull request by SorrenMosher**
Puppeteer system testing framework added. Added a test for the popup.

### CODE REVIEW

**Comment by torisimon2** [comment]
It looks alright just going over the files, I'm just wondering if the test for the popup passes

**Review by torisimon2 — APPROVED** [review]
looks good

**Review by Subpoened-peon — APPROVED** [review]
Looks gouda.

**Review by kdoster — APPROVED** [review]
Looks good

**Pull request merged**
